# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  
  lane :install do
    
    #cocoapods()
    
    desc("Rodando os testes unitários")
    install_scan
    #run_tests(scheme: "DesafioStone")

    desc("Cobertura de Teste")
    slather()


    desc("Rodando os testes de tela")
    capture_screenshots()
  end

  lane :install_cocoapods do 
    desc("Instalando os Pods")
    cocoapods()
  end 

  lane :install_slather do 
    desc("Cobertura de Teste")
    slather(build_directory: "output_covarage",
    input_format: "bah",
    html: true,
    show: true,
    scheme: "DesafioStone",
    proj: "DesafioStone.xcworkspace")
  end

  lane :install_scan do 
    scan(workspace: "DesafioStone.xcworkspace", 
    device: "iPhone 8", 
    scheme: "DesafioStone", 
    code_coverage: true)
  end 

end
