# For a list of all available actions, check out
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#     https://docs.fastlane.tools/plugins/available-plugins

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  
  lane :pipeline do
            
    desc("Rodando os testes unitários")
    run_scan    

    desc("Cobertura de Teste")
    run_slather

    desc("Rodando os testes de tela")
    run_print
 
  end

  lane :run_slather do 
    desc("Cobertura de Teste")
    slather(
      html: true,
      #show: true,
      scheme: "DesafioStone",
      workspace: "DesafioStone.xcworkspace",
      proj: "DesafioStone.xcodeproj",
      output_directory: "fastlane/test_output/slather",
      ignore: [
        "Pods/*",
        "DesafioStone/SupportingFile/*",
        "DesafioStone/App/API/*",
        "DesafioStone/App/Coordinator/*",
        "DesafioStone/App/CoreData/*",
        "DesafioStone/App/Model/*",
        "DesafioStone/App/Helpers/*",
      ])

  end

  lane :run_scan do 
    scan(workspace: "DesafioStone.xcworkspace", 
    device: "iPhone 8", 
    scheme: "DesafioStone", 
    clean: true,
    code_coverage: true,
    skip_testing: ["Pods/*"])
  end 

  lane :run_print do 
    capture_screenshots()
  end

end
